name: 'setup sst'
description: 'Setup SST for Github Ci'
inputs: 
  command:
    description: 'Command to run'
    required: true
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}